# -*- mode: ruby -*-
# vi: set ft=ruby :

# set up master and node and get them talking to each other
# References:
# https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
#

Vagrant.configure('2') do |config|
  box = 'fedora/28-cloud-base'
  master_hostname = 'k8s-master'
  config.vm.define :master, primary: true do |master|
    master.vm.box = box
    master.vm.hostname = master_hostname
    master.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 512
      libvirt.nested = true
    end
    master.vm.provision 'shell', inline: <<-SHELL
      set -x
      dnf update -y
      dnf install -y kubernetes etcd
      sed -ie 's|^\\(KUBE_API_ADDRESS\\)=.*|\\1="--address=0.0.0.0"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_ETCD_SERVERS\\)=.*|\\1="--etcd-servers=http://localhost:2379"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_SERVICE_ADDRESSES\\)=.*|\\1="--service-cluster-ip-range=10.254.0.0/16"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_ADMISSION_CONTROL\\)=.*|\\1="--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(ETCD_LISTEN_CLIENT_URLS\\)=.*|\\1="http://0.0.0.0:2379"|' /etc/etcd/etcd.conf
      systemctl restart etcd kube-apiserver kube-controller-manager kube-scheduler
    SHELL
  end
end