# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.define :master, primary:true do |master| 
    master.vm.box = "fedora/28-cloud-base"
    master.vm.hostname = "k8s-master"
    master.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 2048
      libvirt.nested = true
    end
    master.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y kubernetes etcd
    SHELL
  end

  config.vm.define :minion do |minion| 
    minion.vm.box = "fedora/28-cloud-base"
    minion.vm.hostname = "k8s-minion"
    minion.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 2048
      libvirt.nested = true
    end
    minion.vm.provision "shell", inline: <<-SHELL
      dnf update -y
      dnf install -y kubernetes etcd
    SHELL
  end
 
end
