# -*- mode: ruby -*-
# vi: set ft=ruby :

# set up master and node and get them talking to each other
# References:
# https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
#

nginx_pod = <<-POD
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http
POD

Vagrant.configure('2') do |config|
  box = 'fedora/28-cloud-base'
  master_hostname = 'k8s-master'
  node_hostname = 'k8s-minion'
  config.vm.define :master, primary: true do |master|
    master.vm.box = box
    master.vm.hostname = master_hostname
    master.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 512
      libvirt.nested = true
    end
    master.vm.provision 'shell', inline: <<-SHELL
      set -x
      dnf update -y
      dnf install -y kubernetes etcd
      sed -ie 's|^\\(KUBE_API_ADDRESS\\)=.*|\\1="--address=0.0.0.0"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_ETCD_SERVERS\\)=.*|\\1="--etcd-servers=http://localhost:2379"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_SERVICE_ADDRESSES\\)=.*|\\1="--service-cluster-ip-range=10.254.0.0/16"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(KUBE_ADMISSION_CONTROL\\)=.*|\\1="--admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ResourceQuota"|' /etc/kubernetes/apiserver
      sed -ie 's|^\\(ETCD_LISTEN_CLIENT_URLS\\)=.*|\\1="http://0.0.0.0:2379"|' /etc/etcd/etcd.conf
      systemctl restart etcd kube-apiserver kube-controller-manager kube-scheduler
    SHELL
  end

  node_config = <<-CONFIG
kind: Config
clusters:
- name: local
  cluster:
    server: http://#{master_hostname}:8080
users:
- name: kubelet
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
  CONFIG

  config.vm.define :minion do |minion|
    minion.vm.box = box
    minion.vm.hostname = node_hostname
    minion.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 512
      libvirt.nested = true
    end
    # TODO: replace echo with tee
    minion.vm.provision 'shell', inline: <<-SHELL
      set -x
      dnf update -y
      dnf install -y kubernetes etcd
      sed -ie 's|^\\(KUBE_MASTER\\)=.*|\\1="--master=http://#{master_hostname}:8080"|' /etc/kubernetes/config
      sed -ie 's|^\\(KUBELET_ADDRESS\\)=.*|\\1="--address=0.0.0.0"|' /etc/kubernetes/config
      sed -ie 's|^\\(KUBELET_HOSTNAME\\)=.*|\\1=|" /etc/kubernetes/config
      echo "#{node_config}" > /etc/kubernetes/master-kubeconfig.yaml
      sed -ie 's|^\\(KUBELET_ARGS\\)=.*|\\1="--cgroup-driver=systemd --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml"|' /etc/kubernetes/config
      systemctl restart kube-proxy kubelet docker
    SHELL
  end
end